### ISSUE TITLE
R_emptyEnv for Recipe formula class?

### ISSUE THREAD

**Issue by edwinschut** [tidymodels/butcher#138] opened 2019-09-27 12:55 UTC
When we use butcher on an object of class ”Recipe"  the environment for the “formula” class is set to < R_EmptyEnv>. The recipe is also used in a production chain for preprocessing the data (i.e. "feature engineering"). With a < R_EmptyEnv> this isn’t working any more. 

Is it possible to set this environment to current_env()  or to make it a parameter option?

**Comment by LeenSonneveld** [comment] 2019-09-27 13:02
This seems a Duplicate of #134

**Comment by jyuu** [comment] 2019-09-27 14:47
Thank you! Let me know if the recent fix in this dev version works

**Comment by edwinschut** [comment] 2019-09-30 11:48
Thanks for the update!
For a basic use case it’s ok, but we prefer a change to current_env  instead of base_env.  
We use, for example,  the function year from the lubridate package inside the recipe; with base_env this results in an error because the environment stack doesn’t included the current packages.

**Closed** 2023-03-06 21:27 UTC
Labels: bug
